#!/bin/bash

VERBOSE=${VERBOSE:-0}
MODEL=${MODEL:-"gpt-3.5-turbo-16k"}

prompt="$*"
payload=$(jq -r -c -n \
  --arg model $MODEL \
  --arg prompt "$prompt" \
  --argjson temperature 0 \
  --argjson max_tokens 10000 \
  --argjson top_p 1.0 \
  --argjson frequency_penalty 0.2 \
  --argjson presence_penalty 0.0 \
'{
  "model":$model,
  "messages": [
    {
      "role": "system",
      "content": $prompt
    }
  ],
  "temperature": $temperature,
  "max_tokens": $max_tokens,
  "top_p": $top_p,
  "frequency_penalty": $frequency_penalty,
  "presence_penalty":$presence_penalty
}')

BASE=https://aiapi.cash

data=$(curl -s $BASE/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "$payload")

echo $data | jq '.choices[0].message.content' -r

